### ISSUE TITLE
[BUG] Setup.py fails to install dependencies in Artifactory mirror

### ISSUE THREAD

**Issue by ghost** [djmgit/SaberX#12]
**What is happening**: When running `python3 setup.py install`, pip fails to find the local **pip.conf** file which configures the PyPi mirror.

**What is expected**: Running `python3 setup.py install` should install dependencies from the PyPi Artifactory mirror.

**Steps to reproduce**:

1. Setup an Artifactory PyPi mirror or configure a proxy.
  1. Upload the project dependencies: 
    * pytest
    * psutil
    * flake8
    * pytest-cov
2. Create local **pip.conf** in `~/.pip/pip.conf` (legacy) or consult https://pip.pypa.io/en/stable/user_guide/#config-file on where to create the configuration file.
3. Configure these properties in **pip.conf**:
```
[global]
index-url = https://url.com
trusted-host = url.com
```

**Suggested fix**: A change or enhancement needs to be made in **setup.py** to look for the local **pip.conf**, or at the very least, update the documentation to run the workaround command `pip install -r requirements.txt`.

**Comment by djmgit** [comment]
@britho Hi, thanks a lot for pointing this out.

So what I found out is, python setuptools uses **easy_install** under the hood. So putting the registry url in ~/.pip/pip.conf alone wont help. The following needs to be put under ~/.pydistutils.cfg :

```
[easy_install]
index-url = https://url.com
```
This will allow use to use custom registry.

Also another way, mostly for development purpose, is to install the project with ```develop``` command:

```
python3 setup.py develop --index-url=https://url.com
```
I have updated the doc mentioning the above configs: 
https://saberx.readthedocs.io/en/latest/

I hope now it works for you, otherwise I will reopen the issue and dig further.
